import { NextRequest, NextResponse } from 'next/server';
import { generateAuditNarrative } from '@/lib/llm';
import { insertAuditReport } from '@/lib/supabase';
import type { AuditReport, Citation } from '@/lib/types';

export const runtime = 'nodejs';
export const maxDuration = 60;

const DISCLAIMER =
  'This report was generated by ComplianceAgent (AI-assisted) based on the indexed regulatory documents available at the time of query. It is intended to support, not replace, review by a qualified compliance officer.';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const question: string = body.question;
    const answer: string = body.answer;
    const citations: Citation[] = body.citations || [];
    const queryLogId: string | undefined = body.query_log_id;
    const confidence: 'high' | 'medium' | 'low' = body.confidence || 'medium';

    if (!question || !answer) {
      return NextResponse.json(
        { error: 'question and answer are required' },
        { status: 400 }
      );
    }

    const narrative = await generateAuditNarrative(question, answer, citations);
    const domainsCovered = [...new Set(citations.map((c) => c.title))];

    const report: AuditReport = {
      question,
      answer,
      citations,
      generated_at: new Date().toISOString(),
      domains_covered: domainsCovered,
      disclaimer: DISCLAIMER,
    };

    if (queryLogId) {
      try {
        await insertAuditReport(queryLogId, report);
      } catch (logErr) {
        console.warn('[api/audit] failed to persist audit report', logErr);
      }
    }

    return NextResponse.json({ ...report, narrative });
  } catch (err: any) {
    console.error('[api/audit] error', err);
    return NextResponse.json(
      { error: err?.message || 'Audit report generation failed' },
      { status: 500 }
    );
  }
}
